### PR TITLE
add Theme Switcher.

### LINKED ISSUE #1068: [suggestion]: add a Theme Switcher
I think it would be nice to have a Theme Switcher component that looks more like a tradional Theme Switcher then just text. 

To be clear the text in the footer does not have any issue it works totally fine:

image

But the hard part is merging the above 4 word long string into the Dashboard Layout.

Maybe it would be more feasible to use something like the following instead if the 4 word long strings:

image

### PR DESCRIPTION
**Pull request by nisarhassan12**
Fixes #1068 

This is how it looks:

image

### CODE REVIEW

**Comment by nisarhassan12** [comment]
Currently it needs to be made accessible via Keyboard.

**Comment by nisarhassan12** [comment]
@shicholas I'm unable to run cypress again locally not sure what went wrong:

image

image

Once I have it working again I'll fix the failing specs.

**Comment by nisarhassan12** [comment]
@shicholas What do you think about having the Theme Swicther in the top bar on the Dashboard? Also, I'm not too sure about it's placement on mobile yet. What do you think about placing the sidenavgation at the bottom of the screen on mobile that way we will have enough space in the top bar to have the theme switcher ? 

image

Currently the Dashboard is not well compatible with the Dark mode I think it would make sense to address that in a later Pr.

**Comment by shicholas** [comment]
The portal dashboard looks great, I was also thinking the switcher could be in the `profile` section on the left so we can persist these configurations to the database like #1099 and the related GitHub Issue.

Dashboard looks amazing, thanks!

**Comment by nisarhassan12** [comment]
Thanks, @shicholas. Yeah, it makes sense to move the theme switcher to the profile page. Not too sure though would in it make sense to rename the profile page to something like settings page? i.e we are not gonna have things that are only related to the profile ? Thanks

**Comment by shicholas** [comment]
re: Cypress I'm not sure how to fix this except for the `rm -rf node_modules && yarn`

**Comment by nisarhassan12** [comment]
@shicholas Thanks. I tried it and it didn't work this is What I'm getting:

image

I remember similar sort of issues happened a few months ago which were automatically resolved after re-cloning the repo in a separate directory and then installing the dependencies again. So I'll try that now :)

**Comment by shicholas** [comment]
please 1) run the server with `yarn workspace @neonlaw/interface dev`, 2) change that value to `http://127.0.0.1:800`, and 3) run `yarn workspace @neonlaw/interface cy:open`. You should be good to go from there.

**Comment by nisarhassan12** [comment]
Thanks @shicholas It worked.

**Comment by nisarhassan12** [comment]
@shicholas The PR is ready to be reviewed.

The switch now also works with a keyboard i.e you can switch theme via the enter key once the focus is on the element but for some reason, it behaves quite weirdly with the spacebar key not sure why is that and it is important that It should work with the spacebar key as it does with the enter key.

Peek 2020-11-18 23-02

**Comment by shicholas** [comment]
sounds good, I'll fix the test then merge here

**Pull request merged**
