### PR TITLE
New design for /blog + other small design changes.

### PR DESCRIPTION
**Pull request by nisarhassan12**
This Pr updates the design for `/blog` and also includes some other design changes for the rest of the site.

Initially, I was willing to update the design for the individual blog posts by altering the `MdxLayout` but it turns out that it's being used for all the pages generated from MDX. so changing the design for the blog was causing the layout of other pages as well which is not what I wanted.

I could have gone ahead and refactored the code as needed but that would have made this PR huge and hard to review.

I will make a new separate PR for the design updates for the individual design posts.

This is how `/blog` looks now:

image

### CODE REVIEW

**Comment by nisarhassan12** [comment]
Sorry. I'm not able to run the test suite i.e running `sudo yarn e2e-test` resulted in the following 

image

Also since I have set up docker, other tasks like `yarn install` & `yarn start` are not working I'm getting the permission denied errors so I'm trying `sudo` to make them work.

image

**Comment by shicholas** [comment]
Everything is passing here so going to merge.

To run Cypress tests, try the following:

```bash
docker-compose up interface # run the docker-compose process
```

Then in a separate shell on your machine, run:

```bash
yarn workspace @neonlaw/interface cy:open
```

This will open Cypress on your host machine (it's complicated to run Chrome from within Docker-Compose).

**Comment by nisarhassan12** [comment]
@shicholas I tried the following with `sudo` upfront:

```
yarn workspace @neonlaw/interface cy:open
```

but it does not seem to be working and it looks like stuck here from a few minutes now:

image

**Comment by shicholas** [comment]
do you have Chrome installed on your machine? Otherwise, we'd need to change Cypress to open Firefox instead.

**Comment by nisarhassan12** [comment]
Thanks. I do have it installed and cypress was able to launch it before I started using docker i.e `yarn run e2e-test` used to work perfectly for me in the past.
image

**Comment by shicholas** [comment]
hmm, just to be clear, you've executed these two commands on your `host` and not within a Docker container?

1. `docker-compose up interface`
2. `yarn workspace @neonlaw/interface cy:open`

We can go over that in our sync.

**Comment by nisarhassan12** [comment]
Oops. Sorry. I only ran `yarn workspace @neonlaw/interface cy:open` from my host and thought that running `sudo docker-compose up` would intern start `docker-compose up interface` as in internal task.

**Comment by nisarhassan12** [comment]
Now I tried it as you said i.e

1. I first ran `docker-compose up interface`


image

2. and then ran `yarn workspace @neonlaw/interface cy:open`

but it does not seem to work 

For some reason, it is looking for the global installation of cypress may be:

image

**Comment by shicholas** [comment]
You may have to run `yarn install` from your host too.

**Comment by shicholas** [comment]
Do you have the server running too?

**Comment by nisarhassan12** [comment]
Sorry. I did not have the server running before I think.

Now First I ran:

```
sudo yarn install
```
image



then

```
sudo docker-compose up postgres api
```

image


then in a separate tab once the api was up, ran

```
sudo docker-compose up interface
```

image


and then 

```
yarn workspace @neonlaw/interface cy:open
```

but it seems to fail with this error 

image

**Pull request merged**
