### PR TITLE
Adjust the layout for the questionnarie to make the progress bar visible.

### LINKED ISSUE #643: Progress Bar on questionnaires is hidden behind Navbar
Since the header uses `positioned: fixed` the progress bar is not put in the right scope.

Screen Shot 2020-08-08 at 7 32 08 PM

This should be fixed with a Cypress test.

### PR DESCRIPTION
**Pull request by nisarhassan12**
Fixes #643

This is how it looks:

image

### CODE REVIEW

**Comment by shicholas** [comment]
Do you think we can add the `margin` currently on the `upwardMobilityQuestionnaire` class to the layout? There are other places in the app where the `fixed` navbar overrides the content. e.g. https://www.neonlaw.com/bar-prep/flashcards/?topic=torts

**Comment by nisarhassan12** [comment]
> Do you think we can add the margin currently on the upwardMobilityQuestionnaire class to the layout? 

Thanks, @shicholas. I think no. This will cause the layout to be broken on other pages i.e the HomePage.

> There are other places in the app where the fixed navbar overrides the content. e.g. https://www.neonlaw.com/bar-prep/flashcards/?topic=torts

Sorry. I missed it. Now working on it this is how it looks I have also updated the design a bit so that it looks better:

image

I will soon update the PR with the latest changes that I'm working on.

**Comment by shicholas** [comment]
nice, that looks great.

**Comment by nisarhassan12** [comment]
@shicholas I have update the PR with the fix for the flashcards please have a look whenever you'll have time. Thanks

**Pull request merged**
