### PR TITLE
wip: [dyd] small updates.

### PR DESCRIPTION
**Pull request by nisarhassan12**

### CODE REVIEW

**Comment by nisarhassan12** [comment]
@shicholas With the latest changes on master we are having style conflicts, also the Chakra Color Mode is having un-intented effect on the page.

This is what the page looks lilke now:

image

image

This is caused by the following in `gatsby-ssr.js` and `gatsby-browser.js`:

```jsx
<BaseLayout {...props}>{element}</BaseLayout>
```

I tried removing it and that solved the problem. I did so by replicating the BaseLayout in isolation inside of `/home/nisar/codebase/packages/delete-your-data/src/layouts/base.ts` with the Auth Provider inside of it without incoprating the Charka UI stuff and the base styles in `shared-ui`.

But with chakra-ui stuff removed we could no longer simply use components built on top of it.

I could tailor the footer so that the contents are driven from one source while there are 2 different footer components one inisde DYD and the other  in `shared-ui` which is used by the rest of the site. 

I could also replicate the MDXLayout separately in DYD. Also I would like the blog posts for DYD to have different design and a differnt Layout. Tailoring the existing MDX layout might not turn out to be that much feasible. 

What do you say? Should I go this route? Thanks

**Comment by shicholas** [comment]
Adding the `BaseStyles` was a quick hack to get the footer enabled, I think your solution here is fine. While I know you like building your own components, I'd like to use the work you've already done on NeonLaw.com as much as possible, so I'd like to keep Chakra here. If you logged into the system, you'll see that the portal is the same as the one you've built on NeonLaw, and I'd like to use the same code there too.

Re: blog design, I like what you've already done with https://www.neonlaw.com/blog, and think it could look exactly the same except for colors. For what it's worth the website looks and feels mature now, and I think our development focus should be on adding all the forms required for our users from already-built components, getting our code climate score up, and adding a lot more Cypress tests.

I'm also thinking it might be wise to switch from Gatsby to Next so everything can be the same server-rendered express application. Next supports the idea of having multiple websites in the same codebase, and if we use their hosted solution, Vercel, we can get analytics built-in. This way we don't need a separate `shared-ui` package or 4 different website repos. What do you think? This would be pretty involved, but I think it would enforce a "single-source of truth" as it pertains to our web interfaces which will be invaluable long-term.

**Comment by nisarhassan12** [comment]
> Adding the BaseStyles was a quick hack to get the footer enabled, I think your solution here is fine. While I know you like building your own components, I'd like to use the work you've already done on NeonLaw.com as much as possible, so I'd like to keep Chakra here. If you logged into the system, you'll see that the portal is the same as the one you've built on NeonLaw, and I'd like to use the same code there too.
>
> Re: blog design, I like what you've already done with https://www.neonlaw.com/blog, and think it could look exactly the same except for colors. For what it's worth the website looks and feels mature now, and I think our development focus should be on adding all the forms required for our users from already-built components, getting our code climate score up, and adding a lot more Cypress tests.

Thanks, it makes sense I would try to tailor the DYD to use the Shared UI while extending on what we already have there as a Base in this PR. 

> I'm also thinking it might be wise to switch from Gatsby to Next so everything can be the same server-rendered express application. Next supports the idea of having multiple websites in the same codebase, and if we use their hosted solution, Vercel, we can get analytics built-in. This way we don't need a separate shared-ui package or 4 different website repos. What do you think? This would be pretty involved, but I think it would enforce a "single-source of truth" as it pertains to our web interfaces which will be invaluable long-term.

Thanks while I'm not well familiar enough with Next but from what you told, it sounds worth migrating to Next, having something that would enforce a "single source of truth" would be greatly dividend in terms of maintainability.

Do you have a plan about How and When are we gonna go about migrating to Next?

**Comment by shicholas** [comment]
> > Adding the BaseStyles was a quick hack to get the footer enabled, I think your solution here is fine. While I know you like building your own components, I'd like to use the work you've already done on NeonLaw.com as much as possible, so I'd like to keep Chakra here. If you logged into the system, you'll see that the portal is the same as the one you've built on NeonLaw, and I'd like to use the same code there too.
> > Re: blog design, I like what you've already done with https://www.neonlaw.com/blog, and think it could look exactly the same except for colors. For what it's worth the website looks and feels mature now, and I think our development focus should be on adding all the forms required for our users from already-built components, getting our code climate score up, and adding a lot more Cypress tests.
> 
> Thanks, it makes sense I would try to tailor the DYD to use the Shared UI while extending on what we already have there as a Base in this PR.
> 
> > I'm also thinking it might be wise to switch from Gatsby to Next so everything can be the same server-rendered express application. Next supports the idea of having multiple websites in the same codebase, and if we use their hosted solution, Vercel, we can get analytics built-in. This way we don't need a separate shared-ui package or 4 different website repos. What do you think? This would be pretty involved, but I think it would enforce a "single-source of truth" as it pertains to our web interfaces which will be invaluable long-term.
> 
> Thanks while I'm not well familiar enough with Next but from what you told, it sounds worth migrating to Next, having something that would enforce a "single source of truth" would be greatly dividend in terms of maintainability.
> 
> Do you have a plan about How and When are we gonna go about migrating to Next?

I don't think it's that urgent, just maybe nice-to-have, technically, you can do everything Next does with a fancy Nginx config that might be a viable option too. I think if we move more stuff to `shared-ui` repo it'll be easier to make the switch. Maybe we don't actually need next if we can figure out a way to share components across our neonlaw.com/deleteyourdata.com effectively.

**Comment by shicholas** [comment]
I'll handle the git conflicts then merge this, thanks!

**Comment by nisarhassan12** [comment]
> I'll handle the git conflicts then merge this, thanks!

I feel like this is not yet ready to be merged. Or do you want me to do "I would try to tailor the DYD to use the Shared UI while extending on what we already have there as a Base in this PR." in another PR? Thanks

**Comment by shicholas** [comment]
Please let me merge this first then you can take a fresh crack at `development`. I made a decent amount of edits to bring some `shared-ui` functionality here and fixed the video, and added `chakra` back to this repo.

**Pull request merged**
