### PR TITLE
add search bar up top

### PR DESCRIPTION
**Pull request by nisarhassan12**
This is how it looks: 

image

I have also added the functionality for bringing the search input to focus when the `/` key is pressed.

### CODE REVIEW

**Comment by shicholas** [comment]
this is looking great

**Comment by shicholas** [comment]
@nisarhassan12 can you please merge development and fix the test? I'd like to merge this before we finish the search functionality b/c I don't know how long that will take. I'm fine with having an empty search bar that just focuses for now.

**Comment by shicholas** [comment]
looks great, and looks like just the `index.spec.ts` Cypress spec needs to be updated.

**Comment by nisarhassan12** [comment]
The spec `index.spec.ts` seems to be passing for me locally. Not sure why it's failing in the CI. 

image

image

**Comment by shicholas** [comment]
@nisarhassan12 I'm trying https://github.com/NeonLaw/codebase/pull/601/commits/1427aeb20bb6127782d0092c8345081ffb161554

**Comment by nisarhassan12** [comment]
Thanks @shicholas

**Comment by shicholas** [comment]
looks like the waiting worked

**Pull request merged**
