### PR TITLE
wip: Flash button when selecting it.

### LINKED ISSUE #863: Flash button when selecting it
**Is your feature request related to a problem? Please describe.**
On TypeForm, Stripe, and a few other great websites, when you select a button it will flash for a second, giving the user an indication that that button was what he selected.

**Describe the solution you'd like**
Visit https://www.typeform.com/ and try out the form on the homepage. If you check out the multiple choice question or the 1-10 question and select a choice, you will see the button flash momentarily before calling the click handler associated with that `button`.

### PR DESCRIPTION
**Pull request by nisarhassan12**
Will close #863

### CODE REVIEW

**Comment by nisarhassan12** [comment]
@shicholas I have created a FlashButton component and for now, used it in `Upward Mobility` and `Upward Mobility Questionnaire`. Please have a look at the animation whenever you'll have time. 

Also, Can you outline the places where we're gonna use the Flash button?  Thanks

**Comment by shicholas** [comment]
adding a PR for these buttons sounds good. I imagine all form buttons can be like this.

Can you please keep an outline of the button while it is flashing?

**Comment by nisarhassan12** [comment]
> Can you please keep an outline of the button while it is flashing?

@shicholas  I have added the outline around when the button is flashing This is how it looks.

Peek 2020-10-04 20-04

I'm now working on adding the Flash effect to the other buttons.

**Comment by shicholas** [comment]
that looks great, thanks!

**Pull request merged**
